name = "casal-olives-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_URL = "https://casalolives.concierge.studio"
ADMIN_OWNER_EMAILS = "seb.aquilina@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "studio-vella-db"
database_id = "e6517bcc-8705-47be-93b0-b76ad3c87123"
migrations_dir = "drizzle/migrations"

[[kv_namespaces]]
binding = "DEAD_LETTER"
id = "98054099c25d4a14b4919189a85a6e0e"

[env.preview]
name = "studio-vella-web-preview"

[env.preview.vars]
NEXT_PUBLIC_SITE_URL = "https://preview.studio-vella-web.pages.dev"
ADMIN_OWNER_EMAILS = "seb.aquilina@gmail.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "studio-vella-db-preview"
database_id = "ee96f2d5-4649-4388-a8a8-1b8d8cc682df"
migrations_dir = "drizzle/migrations"
